trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  ResourceGroupName: 'aznew'
  WEB_APP_NAME: 'web2903'
  WEBAPP_PLAN: 'ASP-aznew-b4d0'
  REGION: 'Canada Central'

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'Archive files'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'myfirstserviceconnection'   # <-- use the NAME, not GUID
    appType: 'webAppLinux'
    appName: '$(WEB_APP_NAME)'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
  displayName: 'Deploy to Azure Web App'
